# Generated by Django 4.2.7 on 2023-12-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projeto',
            table='projeto',
        ),
    ]
