# Generated by Django 4.2.7 on 2023-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'projeto', 'verbose_name_plural': 'projetos'},
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(help_text='descrição do projeto', verbose_name='descrição do projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologia',
            field=models.CharField(help_text='tecnologia usada no projeto', max_length=20, verbose_name='tecnologia usada no projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(help_text='título do projeto', max_length=100, verbose_name='título do projeto'),
        ),
    ]
