# Generated by Django 4.2.7 on 2023-12-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_options_alter_projeto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.FileField(blank=True, help_text='Imagem do projeto', upload_to='imagens/', verbose_name='Imagem do projeto'),
        ),
    ]
